services:
  - type: web
    name: stay-connected-bot
    env: node
    plan: free
    buildCommand: npm install
    startCommand: node index.js
    envVars:
      - key: TOKEN
        sync: false
      - key: CHANNEL_ID
        sync: false
